### ISSUE TITLE
Specifying app root is not documented

### ISSUE THREAD

**Issue by kumavis** [twilson63/mercury-router#10]
e.g. on gh-pages root is `username.github.io/repo/`

**Comment by kumavis** [comment]
actually this is provided by an undocumented feature

``` js
state.base = '/repo/'
RouterComponent.render(state, routes)
```

**Comment by kumavis** [comment]
This should be explicit in the readme b/c you might accidentally have a key `base` that it uses

**Comment by twilson63** [comment]
Added API section in the README, please review and let me know if more detail needs to be provided or if I have any errors.

Thx

Tom

**Comment by kumavis** [comment]
thanks!
