### ISSUE TITLE
LICENSE file?

### ISSUE THREAD

**Issue by mynameistechno** [twilson63/mercury-router#13]
Can we add a license file to this project? Preferably same as the mercury project? Thanks!

**Comment by twilson63** [comment]
Sure

Sent from my iPhone

On Aug 29, 2015, at 2:35 PM, Mark Matyas notifications@github.com wrote:

Can we add a license file to this project? Preferably same as the mercury
project? Thanks!

—
Reply to this email directly or view it on GitHub
https://github.com/twilson63/mercury-router/issues/13.
