### ISSUE TITLE
New Direction

### ISSUE THREAD

**Issue by matthewp** [twilson63/mercury-router#5]
Hello all. I wanted to propose a new direction for the router that I think is a better fit both for Mercury and for client-side routers in general.
# Premise

Tying a route to a Handler that creates dom (or vdom) is not the best way to do routing in the client. This is a holdover from the way server-side routing works where the Handler makes more sense. In the server your job is to respond to a request. On the client your job is to respond to **state**.

Handler-based routing causes there to be 2 sources of truth; the route and the state. This makes it difficult to know which to listen to when branching in code, for example. It also forces your app to have routes, taking away possibilities like embedding.

The state should be the single source of truth. The dom and url and 2 different ways to serialize the app state.

```
state -> dom
state -> url

// On popstate
url -> state
```
# Proposal

I love how simple this module is. The only thing I would change is instead of defining routes in a render function with handlers that return vdom, I'd have the user define their routes in their `browser.js` file and provide the state atom. Something like this:

``` js
var route = require('mercury-router');

function App() {
  return mercury.state({
    page: 'home',
    id: mercury.value(null)
  });
}

var app = App();

route('/:page/:id');
route('/', { page: 'home' });
route('/foo/bar', { something: 'else' });
route.atom = app;
```

So routes of `/users/134` would set `page` to "users" and `id` to "134".  As you can see, the second parameter takes an object that lets you define arbitrary properties to set on the state when that route is found. By default it will only set the `params` as provided in the route definition.

This allows your view logic to be ignorant of routes:

``` js
function render(state) {
  switch(state.page) {
    case: 'home':
      return Home.render(state);
    case: 'users':
      return UserProfile.render(state.id);
  }
}
```

On the server you simply don't use `mercury-router`, it's not needed because your render function is pure based on state.
# Questions

I've done some experimentation with this and it works fairly well. There's a couple of I'm unclear on:
1. When the route changes because of a click, for example, do we wipe out the entire state and set only the properties in the route (the params and additional options provided) or do we leave the state alone and only set the specific params that change.
2. Related to the first, how do we handle query parameters? Are those anything that is on state that is not specifically part of the route definition? If so we'd want to way to mark state properties to not be serialized.

Feedback appreciated! @twilson63 @Raynos

**Comment by Raynos** [comment]
> When the route changes because of a click, for example, do we wipe out the entire state and set only the properties in the route (the params and additional options provided) or do we leave the state alone and only set the specific params that change.

This is why routing is how it is right now. 

Note that the way routing works today you can write something like

``` js
function render(state) {
  var page = null;

  if (state.route === '/') {
    page = h('h1', ['Home'])
  } else if (state.route === '/animals') {
    page = h('h1', ['Animals'])
  }

  return h('div', [
    menu(),
    page
  ]);
}
```

We are very close to the idea you have, except your idea is to write the route to multiple fields in the state. This requires nulling out multiple fields in the state when the route changes.

The current idea is that the route is one field in the state, namely the url. This means that nulling the url out is just replacing it.

**Comment by matthewp** [comment]
> We are very close to the idea you have, except your idea is to write the route to multiple fields in the state. This requires nulling out multiple fields in the state when the route changes.

Yep, I don't see a problem with this though, can you elaborate?

Ideally what you _really_ want is to rerun the app's initialization function [as in here](https://github.com/Raynos/mercury/blob/master/examples/server-rendering/browser.js#L8) like you do when doing the server->client hand-off.  Maybe that should be part of the idea some how.

> The current idea is that the route is one field in the state, namely the url. This means that nulling the url out is just replacing it.

Yes, but this unnecessarily ties your app logic to the route. What happens in your example if you want to alias `animal` (singular) to `animals` (plural)?  You have to update everywhere you check in your app to do `if(state.route === '/animals' || state.route === '/animal')`.  With the method I'm proposing you simply need to define a new route in your browser.js:

``` js
route('/:page');
route('/animal', { page: 'animals' });
```

This is all it takes to create an alias. If you define a new route later you don't have to update a dozen places in your code to understand the new route; the code understands normal state properties already. The route is inconsequential.

Also, tying the app logic to a route means you can never run it outside of the context of the webserver. What if your app is a jsfiddle clone and you have routes for `/js`, `/css`, and `/html`. You'd want to be able to embed a fiddle into any arbitrary webpage, but you can't once it depends on routes.

**Comment by Raynos** [comment]
> Yep, I don't see a problem with this though, can you elaborate?

@matthewp let's say your using HTML5 history and your in state XYZ on the app, a complicated state.

The user enters a full url in the address bar to go to state ABC, a completely different complicated state. You would want a way to transition to this smoothly. If you do not null out fields related to XYZ then the state might not transition cleanly.

For example lets say that `/login` sets `loginPopup: true` which renders a full screen popup, if the user goes to `/user/:id` in the url bar, you need to set `loginPopup: false` otherwise he will still have a full screen popup on top of the user page.

**Comment by Raynos** [comment]
> Also, tying the app logic to a route means you can never run it outside of the context of the webserver. 

It sounds like what you want to do is not use the `routeView` helper. I recommend that you write a non-trivial function called `applicationRouteState`

``` js
function applicationRouteState(url) {
  return { ... }
}
```

You can do all of your route handling and aliases in this one function, each time it gets called it will return a clean new object with all the fields nulled out that should be nulled out.

This allows you to decouple your rendering from the url in one place but also not worry about having to reset multiple fields of state.

If you want you can use a chaining dsl similar to the one you suggested to generate this function.
